#!/bin/sh

# usage: kamp-lf [cd-or-select-path]

lf -print-selection "${1:-.}" | tee \
>(wc -l | { read lines; if [ "$lines" -gt 1 ]; then kamp send 'connect terminal kamp-buffers'; fi } ) \
>(xargs --replace --delimiter '\n' kamp edit '{}');
